### ISSUE TITLE
Ensure topologies are DAG

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/policy-machinery#12]
Ensure all topologies are [Directed Acyclic Graphs (DAG)](https://en.wikipedia.org/wiki/Directed_acyclic_graph).

**Comment by Boomatang** [comment]
From what I have found the cgraph library does not ensure that the graph is a DAG. The `graphviz.StrictDirected` is ensuring the graph does not contain multiply direct links from one node to another or self reference links. See [Agstrictdirected](https://graphviz.gitlab.io/graphviz/doxygen/group__cgraph__graph.html#r_ga9bb67e2ef8f18cae6fee03048f35bab3).

For the first iteration of the library and the use case within Kuadrant the fact we are not guaranteed to have a DAG maybe acceptable. I think the only way we can create loops with the policy-machinery is by adding linking functions that creates the circular reference. With the current `Gateway`, `Route` and `Attached Policy` I don't see how we can create a graph with a loop. 

It would be possible to add a check to ensure there is no loops within the graph but this check would be after the creation of the graph. I am not sure if we would be able to resolve any loops at that stage in the process. This post creation check would be a costly check and would only be required when a new node is added to the graph.

What is really needed is someway within the [NewTopology](https://github.com/Kuadrant/policy-machinery/blob/d1458337b918c9d24530007e7ca1ca7e805357eb/machinery/topology.go#L70) to detect that a loop is being created with the link functions. Added that check I believe would be out of scope of getting Kuadrant to GA. 

My opinion is this is a manageable risk and should not stop current progress. For external user of the library it will be more of a risk, but for our use case it is manageable.
